//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PayPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRecord
    {
        [DisplayName("Purchase Time")]
        public Nullable<System.DateTime> txTime { get; set; }
        [DisplayName("First Name")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        public string lastName { get; set; }
        [DisplayName("Session ID")]
        public string sessionID { get; set; }
        [DisplayName("Transaction ID")]
        public string transactionID { get; set; }
        [DisplayName("Quantity Purchased")]
        public string totalTickets { get; set; }
        [DisplayName("Purchase Amount")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> amount { get; set; }
        public string buyerEmail { get; set; }
        public string paymentStatus { get; set; }
    }
}
